name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name:  Link objects
      run: gcc -Wall -std=c11  -o -Icommon_obj/*.o
      
    - name:  Build vendor1
      run: gcc -Wall -std=c11 -Isrc -c ./vendor1/*.c  -o opt
      
    - name: make
      run: make
      
    - name: make
      run: make check
      
    - name: make distcheck
      run: make distcheck
