name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: vendor1
      run: ./vendor1/paho_cs_pub.c
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
