name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install build-essential
      run: sudo apt install build-essential
    
    - name: build vendor1
      run: gcc-o vendor1Exe vendor1/*.c
