name: C Builder

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Link object files
      run: gcc -Wall -std=c11 -o output ./common_obj/*.o
      
    - name: Build
      run: gcc -Wall -std=c11 -Isrc -Icommon_obj ./vendor/*.c  -o opt
    
