name: C Builder

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  Analysis:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install cppcheck static analysis
      run: sudo apt-get update && sudo apt-get install -y cppcheck 
    
    - name: static analysis
      run: cppcheck --suppress=missingIncludeSystem --check-config --force --enable=all --error-exitcode=1 .

   
     
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2 
      with:
          vs-version: 15.0
    
    
    
    - name: msbuild solution build
      run: MSBuild.exe D:\a\sampleSyncDevices\sampleSyncDevices\Device1.sln
    
    
    - name: publish
      run: |
        (echo henry && echo x-ray && echo cardiac && echo N)| D:\a\sampleSyncDevices\sampleSyncDevices\x64\Debug\Device1.exe pub   
      
   
      
   
    
