name: C Builder

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      with:
          vs-version: '[16.4,16.5)'
      
    - name: Cache vcpkg installed
      uses: actions/cache@v1.0.3  
      with:
        path: $VCPKG_ROOT/installed
        key: ${{ runner.os }}-vcpkg-cache-${{ matrix.db-backend }}
      env:
        VCPKG_ROOT: 'C:\vcpkg'
    
    - name: install openssl
      run: vcpkg integrate install; vcpkg install  openssl:x64-windows
    
    - name: Link object files
      run: gcc -Wall -std=c11 -o output ./common_obj/*.c.obj
      
    - name: Build
      run: gcc -Wall -std=c11 -Isrc -Icommon_obj ./vendor/*.c  -o opt
    
