name: C Builder

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up GNU
      uses: actions/setup-gcc-mirror@v1
      
    - name: Build
      run: gcc vendor/*.c
    
