name: C Builder

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install openssl
      run: sudo apt update && apt install build-essential checkinstall zlib1g-dev 
    
    - name: Link object files
      run: gcc -Wall -std=c11 -o output ./common_obj/*.c.obj
      
    - name: Build
      run: gcc -Wall -std=c11 -Isrc -Icommon_obj ./vendor/*.c  -o opt
    
