name: C Builder

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      with:
          vs-version: 15.0
    - name: install npm
      run: npm install
    
    - name: msbuild
      run: MSBuild.exe
      
    - name: Build
      run: gcc -Wall -std=c11 -Isrc -Icommon_obj ./vendor/*.c  -o opt
    
